quarkus.http.test-port=8083
quarkus.http.test-ssl-port=8446
quarkus.http.test-timeout=PT10s
quarkus.http.limits.max-body-size=100M

quarkus.log.console.json.enabled=false
%test,dev,staging.quarkus.log.console.json.enabled=false
quarkus.log.level=INFO
quarkus.log.console.enabled=true
quarkus.log.console.level=INFO

quarkus.smallrye-openapi.info-title=Chatdrex API
%dev.quarkus.smallrye-openapi.info-title=Chatdrex API (development)
%test.quarkus.smallrye-openapi.info-title=Chatdrex API (test)
quarkus.smallrye-openapi.info-version=1.0.1
quarkus.smallrye-openapi.info-description=ChatDRex API provides programmatic access to a conversation-based, multi-agent system for network-based drug repurposing, integrating biomedical knowledge graphs, bioinformatics algorithms, and literature mining for transparent and reproducible in silico analysis.
quarkus.smallrye-openapi.info-terms-of-service=https://www.cosy.bio
quarkus.smallrye-openapi.info-contact-email=simon.suewer@uni-hamburg.de
quarkus.smallrye-openapi.info-contact-name=Cosy Bio Support
quarkus.smallrye-openapi.info-contact-url=https://www.cosy.bio/contact
quarkus.smallrye-openapi.info-license-name=Apache 2.0
quarkus.smallrye-openapi.info-license-url=https://www.apache.org/licenses/LICENSE-2.0.html
quarkus.swagger-ui.always-include=true

#cors
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=/.*/
%dev.quarkus.http.cors.origins=/.*/

#socket
quarkus.websockets-next.server.traffic-logging.enabled=true
quarkus.websockets-next.server.traffic-logging.text-payload-limit=50
quarkus.log.category."io.quarkus.websockets.next.traffic".level=DEBUG

%test,dev.quarkus.websockets-next.server.traffic-logging.enabled=false
%test,dev.quarkus.websockets-next.server.traffic-logging.text-payload-limit=50
%test,dev.quarkus.log.category."io.quarkus.websockets.next.traffic".level=DEBUG
quarkus.websockets-next.server.auto-ping-interval=PT2s

#langchain4j
quarkus.langchain4j.timeout=PT300S
quarkus.langchain4j.chat-model.provider=openai
quarkus.langchain4j.openai.base-url=https://chat.cosy.bio/api
%dev.quarkus.langchain4j.openai.base-url=https://dev.chat.cosy.bio/api
quarkus.langchain4j.guardrails.max-retries=3
#textmode
quarkus.langchain4j.openai.chat-model.model-name=gpt-oss:latest
quarkus.langchain4j.ai.gemini.chat-model.model-id=gemini-2.0-flash
quarkus.langchain4j.openai.api-key=sk-80f5d24ea1ab4bc8ba721a57e4ccd7a8
%dev.quarkus.langchain4j.openai.api-key=sk-90311001da5846e08a1cde507b406533
quarkus.langchain4j.openai.timeout=PT300S
quarkus.langchain4j.openai.max-retries=3
quarkus.langchain4j.openai.chat-model.log-requests=false
quarkus.langchain4j.openai.chat-model.log-responses=false
%test,dev.quarkus.langchain4j.openai.chat-model.log-requests=true
%test,dev.quarkus.langchain4j.openai.chat-model.log-responses=true

#embeddings not used for now
#quarkus.langchain4j.openai.embedding-model.model-name=snowflake-arctic-embed2:latest
#quarkus.langchain4j.pgvector.dimension=1024


#Jackson
quarkus.jackson.accept-case-insensitive-enums=true

# Configure the URL of the REST client
quarkus.rest-client.mygene-client.url=https://mygene.info
quarkus.rest-client.nedrex-client.url=https://api.nedrex.net
%dev.quarkus.rest-client.nedrex-client.url=https://dev.api.nedrex.net
quarkus.rest-client.uniprot-client.url=https://rest.uniprot.org
quarkus.rest-client.semantic-scholar-client.url=https://api.semanticscholar.org/
quarkus.rest-client.pubmed-client.url=https://eutils.ncbi.nlm.nih.gov/
quarkus.rest-client.digest-client.url=https://api.digest-validation.net/

# Chatdrex settings

## Guardtrails
chatdrex.guardtrails.prompt-injection.score.threshold=0.7
chatdrex.guardtrails.prompt-injection.agent.enabled=false
chatdrex.guardtrails.prompt-injection.enabled=true

chatdrex.guardtrails.grounding.score.threshold=0.7
chatdrex.guardtrails.grounding.enabled=false

## KG query
chatdrex.tools.kg-query.retries=3
chatdrex.tools.kg-query.max-result-length=3000
chatdrex.tools.kg-query.min-gene-disorder-score=0.3
chatdrex.tools.kg-query.min-node-score=0.7
chatdrex.tools.kg-query.query-top-node=5

chatdrex.tools.digest.min-score=0.6
chatdrex.tools.digest.top-n=5

#chatdrex.tools.semantic-scholar.api-key=
chatdrex.tools.semantic-scholar.limit=40